# Generated by Django 6.1.1 on 2026-10-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=64)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=16)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at', '-pk'],
                'indexes': [models.Index(fields=['command', '-started_at'], name='jobs_run_command_aea953_idx')],
            },
        ),
    ]
