# Generated by Django 6.1.1 on 2026-10-01 09:28

import django.db.models.deletion
import django.db.models.functions.text
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=16)),
                ('is_group', models.BooleanField(default=False)),
                ('role', models.CharField(blank=True, choices=[('opening_balances', 'Opening Balances'), ('realised_gains', 'Realised Gains'), ('interest', 'Interest'), ('dividends', 'Dividends'), ('rewards', 'Rewards & cashback'), ('interest_paid', 'Interest paid'), ('bank_charges', 'Bank charges & fees'), ('insurance_premiums', 'Insurance premiums'), ('taxes', 'Taxes'), ('uncategorised', 'Uncategorised')], default='', max_length=32)),
                ('asset_class', models.CharField(blank=True, choices=[('equity', 'Equity'), ('debt', 'Debt'), ('gold_silver', 'Gold & silver'), ('real_estate', 'Real estate'), ('cash', 'Cash')], default='', max_length=16)),
                ('emergency_fund_eligible', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='ledger.account')),
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('name')],
            },
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='ledger.account')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=16)),
                ('is_group', models.BooleanField(default=False)),
                ('role', models.CharField(blank=True, choices=[('opening_balances', 'Opening Balances'), ('realised_gains', 'Realised Gains'), ('interest', 'Interest'), ('dividends', 'Dividends'), ('rewards', 'Rewards & cashback'), ('interest_paid', 'Interest paid'), ('bank_charges', 'Bank charges & fees'), ('insurance_premiums', 'Insurance premiums'), ('taxes', 'Taxes'), ('uncategorised', 'Uncategorised')], default='', max_length=32)),
                ('asset_class', models.CharField(blank=True, choices=[('equity', 'Equity'), ('debt', 'Debt'), ('gold_silver', 'Gold & silver'), ('real_estate', 'Real estate'), ('cash', 'Cash')], default='', max_length=16)),
                ('emergency_fund_eligible', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.account')),
            ],
            options={
                'verbose_name': 'historical account',
                'verbose_name_plural': 'historical accounts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAlias',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.account')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical alias',
                'verbose_name_plural': 'historical aliass',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('parent'), name='account_name_unique_in_group', violation_error_message='Another Account in this group has this name.'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('parent', None)), fields=('account_type',), name='one_root_per_type'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('role', ''), _negated=True), fields=('role',), name='role_on_one_account'),
        ),
        migrations.AddConstraint(
            model_name='alias',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('word'), models.F('account'), name='alias_unique_per_account'),
        ),
    ]
