"""PROTOTYPE — Holdings, Term Deposits and Provident Accounts for aa_data. Never merge to main."""

GROW = {
    "ppfas": {
        "name": "Parag Parikh Flexi Cap",
        "kind": "holding",
        "group": "Mutual Funds",
        "mark": "PP",
        "color": "#6B3FA0",
        "balance": 485000.00,
        "start": "1 Apr 2025",
        "holding": {
            "instrument": "Parag Parikh Flexi Cap Fund – Direct Growth",
            "place": "Folio 1234567/89 · CAMS",
            "units": 7412.318,
            "price": 82.63,
            "price_date": "29 Sep",
            "source": "AMFI",
            "stale": False,
            "cost": 485000,
            "xirr": "17.4%",
            "split": "Equity 100% · Flexi Cap",
            "lots": [
                ("5 Jan 2023", "1,538.210", "₹75,000", "Opening Lot"),
                ("5 Feb 2023", "187.425", "₹10,000", ""),
                ("5 Mar 2023", "190.301", "₹10,000", ""),
            ],
            "lots_more": 35,
            "realised_fy": "₹0",
        },
        "earmarks": [("Retirement", "5,000 units", 67)],
        "upcoming": [
            ("Mon 5 Oct", "SIP from SBI Salary", 10000, "Schedule · Retirement"),
        ],
        "line": "₹6,12,489 · +26.3% · XIRR 17.4%",
        "sentence": "Up ₹1,27,489 on ₹4,85,000 put in. 5,000 of its 7,412 units are Earmarked to Retirement.",
        "tiles": [
            ("Units", "7,412.318", "× ₹82.63 NAV, 29 Sep"),
            ("Gain", "+₹1,27,489", "+26.3% on cost"),
            ("XIRR", "17.4%", "Since Jan 2023"),
            ("Retirement", "5,000 units", "2,412 Unallocated"),
        ],
        "terms": [
            ("Instrument", "Parag Parikh Flexi Cap Fund – Direct Growth"),
            ("ISIN", "INF879O01027"),
            ("Held at", "Folio 1234567/89 · CAMS"),
            ("Asset Class split", "Equity 100% (Flexi Cap)"),
            ("Price", "AMFI NAV, daily"),
            ("Funding Account", "SBI Salary"),
            ("Group", "Assets › Mutual Funds"),
        ],
        "strip": "Mutual fund · folio 1234567/89 · equity 100% · AMFI",
    },
    "uti": {
        "name": "UTI Nifty 50 Index",
        "kind": "holding",
        "group": "Mutual Funds",
        "mark": "UTI",
        "color": "#E35205",
        "balance": 331200.00,
        "start": "1 Apr 2025",
        "holding": {
            "instrument": "UTI Nifty 50 Index Fund – Direct Growth",
            "place": "Folio 88213340 · KFintech",
            "units": 2512.004,
            "price": 160.79,
            "price_date": "29 Sep",
            "source": "AMFI",
            "stale": False,
            "cost": 331200,
            "xirr": "13.1%",
            "split": "Equity 100% · Index",
            "lots": [
                ("12 Jun 2022", "2,299.811", "₹3,00,000", "Opening Lot"),
                ("3 Mar 2025", "212.193", "₹31,200", ""),
            ],
            "lots_more": 0,
            "realised_fy": "₹0",
        },
        "earmarks": [("Vacation 2027", "212 units", 8)],
        "upcoming": [],
        "line": "₹4,03,900 · +22.0% · XIRR 13.1%",
        "sentence": "Up ₹72,700 on ₹3,31,200 put in. 212 units are Earmarked to Vacation 2027.",
        "tiles": [
            ("Units", "2,512.004", "× ₹160.79 NAV, 29 Sep"),
            ("Gain", "+₹72,700", "+22.0% on cost"),
            ("XIRR", "13.1%", "Since Jun 2022"),
            ("Vacation 2027", "212 units", "2,300 Unallocated"),
        ],
        "terms": [
            ("Instrument", "UTI Nifty 50 Index Fund – Direct Growth"),
            ("Held at", "Folio 88213340 · KFintech"),
            ("Asset Class split", "Equity 100% (Index)"),
            ("Price", "AMFI NAV, daily"),
            ("Funding Account", "HDFC Savings"),
        ],
        "strip": "Mutual fund · folio 88213340 · equity 100% · AMFI",
    },
    "sgb": {
        "name": "SGB 2023-24 Series III",
        "kind": "holding",
        "group": "Bonds & SGBs",
        "mark": "SGB",
        "color": "#B8860B",
        "balance": 117980.00,
        "start": "1 Apr 2025",
        "holding": {
            "instrument": "SGB 2023-24 Series III (SGBDE31III)",
            "place": "Zerodha · CDSL demat",
            "units": 20,
            "price": 7100.00,
            "price_date": "18 Sep",
            "source": "BSE close",
            "stale": True,
            "cost": 117980,
            "xirr": "14.8%",
            "split": "Gold & silver 100%",
            "lots": [("20 Dec 2023", "20", "₹1,17,980", "Opening Lot")],
            "lots_more": 0,
            "realised_fy": "₹0",
        },
        "earmarks": [],
        "upcoming": [
            ("Sun 20 Dec", "Coupon · 2.50% half-yearly", 1475, "Interest to HDFC"),
        ],
        "line": "₹1,42,000 · price 12 days old",
        "sentence": "20 units at the last BSE close, from 18 Sep — it hasn't traded since. Matures Dec 2031.",
        "tiles": [
            ("Units", "20 g", "× ₹7,100 BSE close"),
            ("Price", "18 Sep", "Stale · 12 days old"),
            ("Gain", "+₹24,020", "+20.4% on cost"),
            ("Next coupon", "20 Dec", "₹1,475 to HDFC"),
        ],
        "terms": [
            ("Instrument", "SGB 2023-24 Series III"),
            ("Held at", "Zerodha · CDSL demat"),
            ("Asset Class split", "Gold & silver 100%"),
            ("Coupon", "2.50% on issue price, half-yearly"),
            ("Matures", "20 Dec 2031"),
            ("Price", "BSE close · staleness window 7 days"),
        ],
        "strip": "SGB · demat CDSL · gold 100% · coupon 2.50% · BSE",
    },
    "flat": {
        "name": "Flat, Whitefield",
        "kind": "holding",
        "group": "Property",
        "mark": "FW",
        "color": "#5B6475",
        "balance": 5800000.00,
        "start": "1 Apr 2025",
        "holding": {
            "instrument": "Flat, Whitefield (manual)",
            "place": "—",
            "units": 1,
            "price": 7200000.00,
            "price_date": "1 Apr",
            "source": "By hand",
            "stale": False,
            "cost": 5800000,
            "xirr": "4.9%",
            "split": "Real estate 100%",
            "lots": [("14 Aug 2021", "1", "₹58,00,000", "Opening Lot")],
            "lots_more": 0,
            "realised_fy": "₹0",
        },
        "earmarks": [],
        "upcoming": [],
        "line": "₹72,00,000 · valued by hand 1 Apr",
        "sentence": "Valued by hand at ₹72,00,000 on 1 Apr. Revalue it within a year to keep it fresh.",
        "tiles": [
            ("Valued", "1 Apr", "By hand · fresh till Mar"),
            ("Cost", "₹58,00,000", "With stamp duty"),
            ("Gain", "+₹14,00,000", "Unrealised"),
            ("Earmarks", "None", "Your home"),
        ],
        "terms": [
            ("Instrument", "Flat, Whitefield (manual)"),
            ("Asset Class split", "Real estate 100%"),
            ("Price", "By hand · staleness window 365 days"),
            ("Group", "Assets › Property"),
        ],
        "strip": "Property · real estate 100% · valued by hand",
    },
    "fd": {
        "name": "HDFC FD ··4417",
        "kind": "deposit",
        "group": "Deposits",
        "mark": "FD",
        "color": "#004C8F",
        "balance": 207163.01,
        "start": "14 Mar 2026",
        "ef": True,
        "deposit": {
            "principal": 200000,
            "rate": "7.10%",
            "compounding": "Quarterly",
            "payout": "Cumulative",
            "opened": "14 Mar 2026",
            "matures": "14 Mar 2027",
            "days": 165,
            "maturity_value": "₹2,14,621",
            "accrued": 645,
            "instruction": "Renew with interest",
            "breakable": True,
            "tds": False,
            "elapsed_pct": 55,
        },
        "earmarks": [("Emergency Fund", "Whole Account", 100)],
        "upcoming": [
            ("Mon 14 Dec", "Interest credit", 3677, "Estimated from terms"),
            (
                "Sun 14 Mar",
                "Matures · renew with interest",
                214621,
                "Asks for new terms",
            ),
        ],
        "line": "Matures 14 Mar 2027 · 7.10%",
        "sentence": "₹2,00,000 at 7.10%, compounding quarterly. It renews with interest on 14 Mar 2027.",
        "tiles": [
            ("Matures", "14 Mar 2027", "165 days · renews"),
            ("At maturity", "₹2,14,621", "Cumulative"),
            ("Accrued", "₹645", "Since 14 Sep · not counted"),
            ("Emergency Fund", "Whole", "Breakable bank FD"),
        ],
        "terms": [
            ("Kind", "Bank FD"),
            ("Principal", "₹2,00,000 on 14 Mar 2026"),
            ("Rate", "7.10% for the term"),
            ("Compounding", "Quarterly"),
            ("Payout", "Cumulative"),
            ("Maturity instruction", "Renew, principal + interest"),
            ("Breakable", "Yes · Emergency-Fund eligible"),
            ("TDS split", "Off"),
        ],
        "strip": "Bank FD · 7.10% quarterly · cumulative · matures 14 Mar 2027",
    },
    "ppf": {
        "name": "PPF · SBI",
        "kind": "provident",
        "group": "Retirement",
        "mark": "PPF",
        "color": "#146C94",
        "balance": 510000.00,
        "start": "1 Apr 2025",
        "provident": {
            "scheme": "PPF",
            "rate": "7.1%",
            "rate_note": "Jul–Sep 2026",
            "fy_in": 60000,
            "fy_max": 150000,
            "fy_pct": 40,
            "accrued": 22100,
            "credit": ("31 Mar 2027", "₹38,900", "Estimated"),
            "matures": "1 Apr 2035",
            "status": "Minimum ₹500 met for 2026-27",
        },
        "earmarks": [("Retirement", "Whole Account", 100)],
        "upcoming": [
            ("Mon 5 Oct", "Deposit from HDFC", 10000, "Schedule · by the 5th"),
            ("Wed 31 Mar", "Interest for 2026-27", 38900, "Estimated"),
        ],
        "line": "₹60,000 of ₹1.5 L in 2026-27",
        "sentence": "₹60,000 in this year of ₹1,50,000 allowed. About ₹38,900 interest lands on 31 Mar.",
        "tiles": [
            ("This FY", "₹60,000", "of ₹1,50,000 limit"),
            ("Accrued", "₹22,100", "Since 1 Apr · not counted"),
            ("Rate", "7.1%", "Jul–Sep 2026"),
            ("Matures", "1 Apr 2035", "Extend in 5-year blocks"),
        ],
        "terms": [
            ("Scheme", "PPF"),
            ("Opened", "12 Jul 2019 (FY 2019-20)"),
            ("Matures", "1 Apr 2035"),
            ("Rate", "7.1% · scheme rate table"),
            ("Yearly limits", "₹500 – ₹1,50,000"),
            ("Interest credited", "31 March, yearly"),
        ],
        "strip": "PPF · 7.1% · ₹60,000 of ₹1.5 L this FY · matures 2035",
    },
    "epf": {
        "name": "EPF",
        "kind": "provident",
        "group": "Retirement",
        "mark": "EPF",
        "color": "#1F7A5A",
        "balance": 785300.00,
        "start": "1 Apr 2025",
        "provident": {
            "scheme": "EPF",
            "rate": "8.25%",
            "rate_note": "FY 2025-26",
            "fy_in": 129600,
            "fy_max": None,
            "fy_pct": None,
            "accrued": 29800,
            "credit": ("31 Mar 2026", "₹52,400", "Due · overdue after today"),
            "matures": "At retirement",
            "status": "₹21,600 a month via payslip",
        },
        "earmarks": [("Retirement", "Whole Account", 100)],
        "upcoming": [
            (
                "Tue 31 Mar",
                "Interest for 2025-26",
                52400,
                "Due since 31 Mar · estimated",
            ),
        ],
        "line": "2025-26 interest still due",
        "sentence": "Interest for 2025-26 hasn't been credited yet — about ₹52,400. Confirm it when the passbook shows it.",
        "tiles": [
            ("2025-26 interest", "₹52,400", "Due · overdue from tomorrow"),
            ("This FY in", "₹1,29,600", "₹21,600 a month via payslip"),
            ("Accrued", "₹29,800", "Since 1 Apr · not counted"),
            ("Rate", "8.25%", "FY 2025-26"),
        ],
        "terms": [
            ("Scheme", "EPF"),
            ("UAN", "1009 8123 4471"),
            ("Rate", "8.25% (FY 2025-26) · scheme rate table"),
            ("Contributions", "Via the payslip Transaction"),
            ("Interest credited", "31 March, yearly · 6 months' grace"),
        ],
        "strip": "EPF · 8.25% FY26 · via payslip · 2025-26 interest due",
    },
}
