"""PROTOTYPE — sample Transactions for aa_data. Never merge to main."""

from datetime import date

# (id, date, time, payee, kind, headline amount, postings, extra)
# Postings: (account slug or leaf, INR, units or None). Dr +, Cr −.
TXNS = [
    (
        1,
        date(2026, 9, 30),
        "9:14 pm",
        "Swiggy",
        "spending",
        -486,
        [("Dining out", 486, None), ("icici", -486, None)],
        {"source": "Quick-add · “486 swiggy card”"},
    ),
    (
        2,
        date(2026, 9, 30),
        "6:02 pm",
        "BigBasket",
        "spending",
        -2134.50,
        [("Groceries", 2134.50, None), ("hdfc", -2134.50, None)],
        {"source": "Quick-add"},
    ),
    (
        3,
        date(2026, 9, 30),
        "9:40 am",
        "Uber",
        "spending",
        -312,
        [("Transport", 312, None), ("icici", -312, None)],
        {"source": "Quick-add"},
    ),
    (
        4,
        date(2026, 9, 29),
        "7:48 pm",
        "HP Petrol, Indiranagar",
        "spending",
        -1500,
        [("Fuel", 1500, None), ("icici", -1500, None)],
        {"source": "Quick-add"},
    ),
    (
        5,
        date(2026, 9, 29),
        "4:15 pm",
        "Ravi Kumar",
        "spending",
        -2000,
        [("Uncategorised", 2000, None), ("hdfc", -2000, None)],
        {
            "source": "Quick-add · “2000 ravi” — no Account matched",
            "flag": "Uncategorised",
        },
    ),
    (
        6,
        date(2026, 9, 29),
        "11:20 am",
        "BESCOM",
        "spending",
        -1860,
        [("Electricity", 1860, None), ("hdfc", -1860, None)],
        {"source": "Quick-add"},
    ),
    (
        7,
        date(2026, 9, 28),
        "10:00 am",
        "Acme Technologies",
        "income",
        155400,
        [
            ("sbi", 155400, None),
            ("TDS", 28600, None),
            ("Professional tax", 200, None),
            ("epf", 21600, None),
            ("Salary", -195000, None),
            ("Employer EPF", -10800, None),
        ],
        {
            "source": "Confirmed from Schedule “Salary · Acme”",
            "fulfils": "Salary · Acme · 28 Sep",
        },
    ),
    (
        8,
        date(2026, 9, 28),
        "10:02 am",
        "SBI Home loan EMI",
        "transfer",
        -38500,
        [
            ("homeloan", 11285, None),
            ("Home loan interest", 27215, None),
            ("sbi", -38500, None),
        ],
        {
            "source": "Confirmed from the Loan's EMI",
            "fulfils": "SBI Home loan EMI · 28 Sep",
        },
    ),
    (
        9,
        date(2026, 9, 27),
        "8:30 pm",
        "Toit, Indiranagar",
        "spending",
        -3480,
        [("Dining out", 3480, None), ("icici", -3480, None)],
        {"source": "Quick-add", "tags": ["Anniversary"], "note": "Dinner with Meera"},
    ),
    (
        10,
        date(2026, 9, 26),
        "1:12 pm",
        "IndiGo",
        "spending",
        -8420,
        [("Travel", 8420, None), ("icici", -8420, None)],
        {"source": "Quick-add", "tags": ["Goa trip"], "note": "BLR–GOI return, 2 pax"},
    ),
    (
        11,
        date(2026, 9, 26),
        "1:30 pm",
        "Airbnb",
        "spending",
        -12600,
        [("Travel", 12600, None), ("hdfc", -12600, None)],
        {"source": "Quick-add", "tags": ["Goa trip"]},
    ),
    (
        12,
        date(2026, 9, 14),
        "9:00 am",
        "HDFC FD interest",
        "income",
        3613.01,
        [("fd", 3613.01, None), ("Interest", -3613.01, None)],
        {
            "source": "Auto-posted from the deposit's terms",
            "fulfils": "HDFC FD ··4417 interest · 14 Sep",
        },
    ),
    (
        13,
        date(2026, 9, 10),
        "7:05 pm",
        "ICICI card bill",
        "transfer",
        -21870,
        [("icici", 21870, None), ("hdfc", -21870, None)],
        {
            "source": "Confirmed from the Card's bill",
            "fulfils": "ICICI card bill · 22 Aug statement",
        },
    ),
    (
        14,
        date(2026, 9, 5),
        "10:05 am",
        "Parag Parikh SIP",
        "investment",
        -10000,
        [("ppfas", 10000, 121.049), ("sbi", -10000, None)],
        {
            "source": "Confirmed from Schedule; linked to CAS import · 12 Sep",
            "fulfils": "Parag Parikh SIP · 5 Sep",
            "note": "NAV ₹82.61 · stamp duty ₹0.50 in cost",
        },
    ),
    (
        15,
        date(2026, 9, 5),
        "9:30 am",
        "PPF deposit",
        "investment",
        -10000,
        [("ppf", 10000, None), ("hdfc", -10000, None)],
        {"source": "Confirmed from Schedule", "fulfils": "PPF deposit · 5 Sep"},
    ),
    (
        16,
        date(2026, 9, 1),
        "8:00 am",
        "Mr. Rao",
        "spending",
        -32000,
        [("Rent", 32000, None), ("hdfc", -32000, None)],
        {
            "source": "Auto-posted from Schedule “Rent to Mr. Rao”",
            "fulfils": "Rent to Mr. Rao · 1 Sep",
        },
    ),
    (
        17,
        date(2026, 8, 28),
        "10:00 am",
        "Acme Technologies",
        "income",
        155400,
        [
            ("sbi", 155400, None),
            ("TDS", 28600, None),
            ("Professional tax", 200, None),
            ("epf", 21600, None),
            ("Salary", -195000, None),
            ("Employer EPF", -10800, None),
        ],
        {
            "source": "Confirmed from Schedule “Salary · Acme”",
            "fulfils": "Salary · Acme · 28 Aug",
        },
    ),
    (
        18,
        date(2026, 8, 28),
        "10:02 am",
        "SBI Home loan EMI",
        "transfer",
        -38500,
        [
            ("homeloan", 11207, None),
            ("Home loan interest", 27293, None),
            ("sbi", -38500, None),
        ],
        {
            "source": "Confirmed from the Loan's EMI",
            "fulfils": "SBI Home loan EMI · 28 Aug",
        },
    ),
    (
        19,
        date(2026, 8, 22),
        "12:00 am",
        "iPhone 16 instalment",
        "transfer",
        -5217,
        [("iphone", 5217, None), ("icici", -5217, None)],
        {"source": "Auto-posted from the Card EMI"},
    ),
]

TAGS = ["Goa trip", "Anniversary"]
