"""PROTOTYPE — sample Policies and Dependents for the Plan tab screens ticket. Never merge to main."""

PEOPLE = [
    {
        "key": "you",
        "name": "You",
        "rel": "Akshay · 36",
        "relies": None,
        "health": 3500000,
        "health_text": "₹35 L",
        "health_how": "₹10 L floater + ₹25 L top-up",
        "health_gap": 0,
    },
    {
        "key": "priya",
        "name": "Priya",
        "rel": "Spouse · 34 · relies on your income",
        "relies": True,
        "health": 3500000,
        "health_text": "₹35 L",
        "health_how": "₹10 L floater + ₹25 L top-up",
        "health_gap": 0,
    },
    {
        "key": "aarav",
        "name": "Aarav",
        "rel": "Son · 6 · relies on your income",
        "relies": True,
        "health": 1000000,
        "health_text": "₹10 L",
        "health_how": "₹10 L floater · top-up doesn't cover him",
        "health_gap": 0,
    },
    {
        "key": "amma",
        "name": "Amma",
        "rel": "Mother · 64 · has her own pension",
        "relies": False,
        "health": 0,
        "health_text": "₹0",
        "health_how": "Employer ₹5 L shown, not counted",
        "health_gap": 1000000,
    },
]

FLOOR = 1000000
LIFE = {
    "need": "₹2.26 Cr",
    "counted": "₹1.05 Cr",
    "gap": "₹1.21 Cr",
    "pct": 46,
    "how": "10 × Take-home ₹18.6 L + Liabilities ₹41.5 L − unearmarked liquid ₹1.1 L",
}

# counts: life | health | none. status: ok | soon | lapsed
POLICIES = {
    "term": {
        "name": "HDFC Click 2 Protect Super",
        "insurer": "HDFC Life",
        "number": "C2P-2203-88417",
        "type": "Term life",
        "counts": "life",
        "cover": "₹1 Cr",
        "cover_raw": 10000000,
        "persons": ["You"],
        "life_assured": "You",
        "start": "14 Mar 2022",
        "until": "14 Mar 2027",
        "renewal": "1 year · policy term to Mar 2057",
        "premium": ("HDFC term premium", "₹18,900 yearly · next 14 Mar 2027", "term"),
        "employer": False,
        "deductible": None,
        "nominees": [("Priya", "100%")],
        "riders": [("Accidental death benefit", "₹25 L")],
        "holdings": [],
        "notes": "",
        "status": "ok",
        "when": "Paid to 14 Mar 2027",
        "verdict": "Counts ₹1 Cr toward your life cover.",
        "icon": "heart-handshake",
    },
    "endow": {
        "name": "LIC Jeevan Anand",
        "insurer": "LIC",
        "number": "71 884 2019",
        "type": "Endowment",
        "counts": "life",
        "cover": "₹5 L",
        "cover_raw": 500000,
        "persons": ["You"],
        "life_assured": "You",
        "start": "28 Dec 2014",
        "until": "28 Dec 2026",
        "renewal": "1 year · premiums until Dec 2035",
        "premium": ("LIC premium", "₹24,000 yearly · next 28 Dec · to the Holding", "lic"),
        "employer": False,
        "deductible": None,
        "nominees": [("Amma", "50%"), ("Priya", "50%")],
        "riders": [],
        "holdings": [("LIC Jeevan Anand · surrender value", "₹2,86,400 · revalued by hand 31 Mar")],
        "notes": "Bought by Appa in 2014.",
        "status": "ok",
        "when": "Paid to 28 Dec",
        "verdict": "Counts ₹5 L toward your life cover. Its value sits in a Holding.",
        "icon": "piggy-bank",
    },
    "star": {
        "name": "Star Health Family Floater",
        "insurer": "Star Health",
        "number": "P/181216/01/2026/004412",
        "type": "Health · base",
        "counts": "health",
        "cover": "₹10 L",
        "cover_raw": 1000000,
        "persons": ["You", "Priya", "Aarav"],
        "life_assured": None,
        "start": "18 Oct 2021",
        "until": "18 Oct 2026",
        "renewal": "1 year",
        "premium": ("Star Health premium", "₹28,450 due 18 Oct", "star"),
        "employer": False,
        "deductible": None,
        "nominees": [("Priya", "100%")],
        "riders": [("Room-rent waiver", "—")],
        "holdings": [],
        "notes": "",
        "status": "soon",
        "when": "Renews in 18 days",
        "verdict": "A floater: counts the full ₹10 L for each of You, Priya and Aarav.",
        "icon": "stethoscope",
    },
    "care": {
        "name": "Care Supreme Super Top-up",
        "insurer": "Care Health",
        "number": "CS-7729-014",
        "type": "Health · super top-up",
        "counts": "health",
        "cover": "₹25 L over ₹10 L",
        "cover_raw": 2500000,
        "persons": ["You", "Priya"],
        "life_assured": None,
        "start": "2 Jan 2025",
        "until": "2 Jan 2027",
        "renewal": "1 year",
        "premium": None,
        "employer": False,
        "deductible": "₹10 L",
        "nominees": [("Priya", "100%")],
        "riders": [],
        "holdings": [],
        "notes": "Premium paid by card; no Schedule set.",
        "status": "ok",
        "when": "Cover to 2 Jan · no premium Schedule",
        "verdict": "Counts ₹25 L for You and Priya, whose counted base cover (₹10 L) reaches its ₹10 L deductible.",
        "icon": "stethoscope",
    },
    "acme": {
        "name": "Acme group health",
        "insurer": "ICICI Lombard (via Acme)",
        "number": "GMC-ACME-2026",
        "type": "Health · base",
        "counts": "none",
        "cover": "₹5 L",
        "cover_raw": 500000,
        "persons": ["You", "Priya", "Aarav", "Amma"],
        "life_assured": None,
        "start": "1 Apr 2026",
        "until": "31 Mar 2027",
        "renewal": "1 year",
        "premium": None,
        "employer": True,
        "deductible": None,
        "nominees": [],
        "riders": [],
        "holdings": [],
        "notes": "Ends if you leave Acme.",
        "status": "ok",
        "when": "Employer-provided",
        "verdict": "Employer-provided: shown, never counted. It ends with the job.",
        "icon": "building-2",
    },
    "motor": {
        "name": "ICICI Lombard car policy",
        "insurer": "ICICI Lombard",
        "number": "3001/MT/58821",
        "type": "Motor",
        "counts": "none",
        "cover": "₹6.8 L IDV",
        "cover_raw": 680000,
        "persons": ["You"],
        "life_assured": None,
        "start": "9 Feb 2026",
        "until": "9 Feb 2027",
        "renewal": "1 year",
        "premium": None,
        "employer": False,
        "deductible": None,
        "nominees": [],
        "riders": [("Zero depreciation", "—")],
        "holdings": [],
        "notes": "",
        "status": "ok",
        "when": "Cover to 9 Feb",
        "verdict": "Motor: recorded only, never counted by the Doctrine.",
        "icon": "car",
    },
}
