"""PROTOTYPE — sample Schedules for the Plan tab screens ticket. Never merge to main."""

SCHEDULES = {
    "salary": {
        "name": "Salary · Acme",
        "cls": "income",
        "every": "Monthly on the 28th",
        "amount": 155400,
        "estimated": True,
        "mode": "Confirm",
        "icon": "briefcase",
        "color": "#0A8754",
        "template": [
            ("Gross salary", "−₹1,95,000"),
            ("Income tax (TDS)", "+₹28,600"),
            ("EPF", "+₹11,000"),
            ("SBI Salary", "+₹1,55,400"),
        ],
        "next": "Wed 28 Oct",
        "notes": ["Pre-fills last month's actual: ₹1,55,400"],
        "flag": "",
    },
    "sip": {
        "name": "Parag Parikh Flexi Cap SIP",
        "cls": "savings",
        "every": "Monthly on the 5th",
        "amount": 10000,
        "estimated": False,
        "mode": "Confirm",
        "icon": "chart-line",
        "color": "#5B2C83",
        "template": [("PPFAS Flexi Cap · units at the day's NAV", "+₹10,000"), ("SBI Salary", "−₹10,000")],
        "next": "Mon 5 Oct",
        "notes": ["Steps up 10% every April · ₹11,000 from Apr 2027", "Units earmarked to Retirement"],
        "flag": "",
    },
    "ppf": {
        "name": "PPF deposit",
        "cls": "savings",
        "every": "Monthly on the 5th",
        "amount": 10000,
        "estimated": False,
        "mode": "Auto-post",
        "icon": "piggy-bank",
        "color": "#1F6F43",
        "template": [("PPF", "+₹10,000"), ("HDFC Savings", "−₹10,000")],
        "next": "Mon 5 Oct",
        "notes": ["₹60,000 of ₹1,50,000 deposited in 2026-27"],
        "flag": "",
    },
    "europe": {
        "name": "Europe 2028 SIP",
        "cls": "savings",
        "every": "Monthly on the 10th",
        "amount": 5000,
        "estimated": False,
        "mode": "Confirm",
        "icon": "plane",
        "color": "#0E7C86",
        "template": [("Nifty 50 index fund", "+₹5,000"), ("HDFC Savings", "−₹5,000")],
        "next": "Sat 10 Oct",
        "notes": ["Units earmarked to Europe 2028"],
        "flag": "Out of order — funds a Goal while Stage 3 (Protection) is unmet",
    },
    "rent": {
        "name": "Rent to Mr. Rao",
        "cls": "committed",
        "every": "Monthly on the 1st",
        "amount": 32000,
        "estimated": False,
        "mode": "Auto-post",
        "icon": "house",
        "color": "#2A6FDB",
        "template": [("Rent", "+₹32,000"), ("HDFC Savings", "−₹32,000")],
        "next": "Thu 1 Oct",
        "notes": ["₹33,600 from 1 Jan 2027 (lease renewal)"],
        "flag": "",
    },
    "help": {
        "name": "Domestic help · Sunita",
        "cls": "committed",
        "every": "Monthly on the 25th",
        "amount": 6000,
        "estimated": False,
        "mode": "Confirm",
        "icon": "house",
        "color": "#0B9B6A",
        "template": [("Domestic help", "+₹6,000"), ("Cash", "−₹6,000")],
        "next": "Sun 25 Oct",
        "notes": [],
        "flag": "",
    },
    "bescom": {
        "name": "BESCOM electricity",
        "cls": "committed",
        "every": "Monthly on the 22nd",
        "amount": 2340,
        "estimated": True,
        "mode": "Confirm",
        "icon": "zap",
        "color": "#E0A800",
        "template": [("Electricity", "+~₹2,340"), ("HDFC Savings", "−~₹2,340")],
        "next": "Thu 22 Oct",
        "notes": ["Pre-fills the last actual amount"],
        "flag": "",
    },
    "airtel": {
        "name": "Airtel broadband",
        "cls": "committed",
        "every": "Monthly on the 2nd",
        "amount": 1179,
        "estimated": True,
        "mode": "Confirm",
        "icon": "wifi",
        "color": "#E4002B",
        "template": [("Internet & DTH", "+~₹1,179"), ("HDFC Savings", "−~₹1,179")],
        "next": "Fri 2 Oct",
        "notes": [],
        "flag": "",
    },
    "netflix": {
        "name": "Netflix",
        "cls": "committed",
        "every": "Monthly on the 14th",
        "amount": 649,
        "estimated": False,
        "mode": "Auto-post",
        "icon": "clapperboard",
        "color": "#B20710",
        "template": [("Subscriptions", "+₹649"), ("ICICI Amazon Pay", "−₹649")],
        "next": "Wed 14 Oct",
        "notes": [],
        "flag": "",
    },
    "cult": {
        "name": "Cult.fit membership",
        "cls": "committed",
        "every": "Monthly on the 3rd",
        "amount": 2499,
        "estimated": False,
        "mode": "Auto-post",
        "icon": "dumbbell",
        "color": "#111111",
        "template": [("Fitness", "+₹2,499"), ("ICICI Amazon Pay", "−₹2,499")],
        "next": "Thu 3 Dec",
        "notes": [],
        "flag": "",
        "paused": "Paused 1 Sep – 30 Nov",
    },
    "star": {
        "name": "Star Health premium",
        "cls": "committed",
        "every": "Yearly on 18 Oct",
        "amount": 28450,
        "estimated": False,
        "mode": "Confirm",
        "icon": "shield",
        "color": "#1C7C54",
        "template": [("Insurance premiums", "+₹28,450"), ("HDFC Savings", "−₹28,450")],
        "next": "Sun 18 Oct",
        "notes": ["Linked to the Star Health Family Floater Policy"],
        "flag": "",
    },
    "term": {
        "name": "HDFC term premium",
        "cls": "committed",
        "every": "Yearly on 14 Mar",
        "amount": 18900,
        "estimated": False,
        "mode": "Confirm",
        "icon": "shield",
        "color": "#004C8F",
        "template": [("Insurance premiums", "+₹18,900"), ("HDFC Savings", "−₹18,900")],
        "next": "Sun 14 Mar 2027",
        "notes": ["Linked to HDFC Click 2 Protect"],
        "flag": "",
    },
    "lic": {
        "name": "LIC premium",
        "cls": "savings",
        "every": "Yearly on 28 Dec",
        "amount": 24000,
        "estimated": False,
        "mode": "Confirm",
        "icon": "piggy-bank",
        "color": "#F2B300",
        "template": [("LIC Jeevan Anand", "+₹24,000"), ("HDFC Savings", "−₹24,000")],
        "next": "Mon 28 Dec",
        "notes": ["Linked to the LIC Jeevan Anand Policy · whole premium to its Holding"],
        "flag": "",
    },
}

# Occurrences that come from an Account's own terms, not a Schedule.
FROM_TERMS = [
    ("SBI Home loan EMI", "Loan · 28th · ₹38,500 · ends Mar 2041", "house", "#2A6FDB"),
    ("ICICI card bill", "Card · due the 12th · statement amount", "credit-card", "#B02A30"),
    ("HDFC FD interest", "Term Deposit · cumulative · matures 14 Jan 2027", "landmark", "#004C8F"),
    ("EPF interest", "Provident · 31 Mar yearly · scheme rate", "landmark", "#1F6F43"),
    ("PPF interest", "Provident · 31 Mar yearly · 7.1%", "landmark", "#1F6F43"),
]

MONTHLY = {"in": 155400, "savings": 25000, "committed": 80668, "net": 49732}
