"""PROTOTYPE — sample Occurrences and Schedules for the Plan tab screens ticket. Never merge to main."""

# status: overdue | today | soon | later | done. cls: income | savings | committed | excluded
OCCURRENCES = [
    {
        "key": "bescom",
        "name": "BESCOM electricity",
        "date": "Tue 22 Sep",
        "short": "22 Sep",
        "amount": 2340,
        "estimated": True,
        "status": "overdue",
        "late": "8 days overdue",
        "source": "Schedule · estimated",
        "schedule": "bescom",
        "from": "HDFC Savings",
        "to": "Electricity",
        "cls": "committed",
        "icon": "zap",
        "color": "#E0A800",
        "match": {
            "payee": "BESCOM",
            "date": "Thu 24 Sep",
            "amount": 2288,
            "from": "HDFC Savings",
            "to": "Electricity",
            "how": "quick-add",
            "why": "Hits Electricity, 2 days after, any amount (estimated)",
        },
    },
    {
        "key": "help",
        "name": "Domestic help · Sunita",
        "date": "Fri 25 Sep",
        "short": "25 Sep",
        "amount": 6000,
        "estimated": False,
        "status": "overdue",
        "late": "5 days overdue",
        "source": "Schedule · fixed",
        "schedule": "help",
        "from": "Cash",
        "to": "Domestic help",
        "cls": "committed",
        "icon": "house",
        "color": "#0B9B6A",
        "match": None,
    },
    {
        "key": "epf",
        "name": "EPF interest 2025-26",
        "date": "Tue 31 Mar",
        "short": "31 Mar",
        "amount": 38920,
        "estimated": True,
        "status": "today",
        "late": "Overdue from tomorrow",
        "source": "EPF · scheme rate 8.25%",
        "schedule": None,
        "from": "Interest",
        "to": "EPF",
        "cls": "income",
        "icon": "landmark",
        "color": "#1F6F43",
        "match": None,
    },
    {
        "key": "rent",
        "name": "Rent to Mr. Rao",
        "date": "Thu 1 Oct",
        "short": "1 Oct",
        "amount": 32000,
        "estimated": False,
        "status": "soon",
        "late": "Posts itself",
        "source": "Schedule · fixed · auto-post",
        "schedule": "rent",
        "from": "HDFC Savings",
        "to": "Rent",
        "cls": "committed",
        "icon": "house",
        "color": "#2A6FDB",
        "match": None,
    },
    {
        "key": "airtel",
        "name": "Airtel broadband",
        "date": "Fri 2 Oct",
        "short": "2 Oct",
        "amount": 1179,
        "estimated": True,
        "status": "soon",
        "late": "",
        "source": "Schedule · estimated",
        "schedule": "airtel",
        "from": "HDFC Savings",
        "to": "Internet & DTH",
        "cls": "committed",
        "icon": "wifi",
        "color": "#E4002B",
        "match": None,
    },
    {
        "key": "sip",
        "name": "Parag Parikh Flexi Cap SIP",
        "date": "Mon 5 Oct",
        "short": "5 Oct",
        "amount": 10000,
        "estimated": False,
        "status": "soon",
        "late": "",
        "source": "Schedule · fixed · Retirement",
        "schedule": "sip",
        "from": "SBI Salary",
        "to": "PPFAS Flexi Cap",
        "cls": "savings",
        "icon": "chart-line",
        "color": "#5B2C83",
        "match": None,
    },
    {
        "key": "ppf",
        "name": "PPF deposit",
        "date": "Mon 5 Oct",
        "short": "5 Oct",
        "amount": 10000,
        "estimated": False,
        "status": "soon",
        "late": "",
        "source": "Schedule · fixed",
        "schedule": "ppf",
        "from": "HDFC Savings",
        "to": "PPF",
        "cls": "savings",
        "icon": "piggy-bank",
        "color": "#1F6F43",
        "match": None,
    },
    {
        "key": "icici",
        "name": "ICICI card bill",
        "date": "Mon 12 Oct",
        "short": "12 Oct",
        "amount": 23410,
        "estimated": False,
        "status": "later",
        "late": "",
        "source": "Card · pay in full",
        "schedule": None,
        "from": "HDFC Savings",
        "to": "ICICI Amazon Pay",
        "cls": "excluded",
        "icon": "credit-card",
        "color": "#B02A30",
        "match": None,
    },
    {
        "key": "star",
        "name": "Star Health renewal premium",
        "date": "Sun 18 Oct",
        "short": "18 Oct",
        "amount": 28450,
        "estimated": False,
        "status": "later",
        "late": "",
        "source": "Schedule · yearly · rolls cover to 18 Oct 2027",
        "schedule": "star",
        "from": "HDFC Savings",
        "to": "Insurance premiums",
        "cls": "committed",
        "icon": "shield",
        "color": "#1C7C54",
        "match": None,
    },
    {
        "key": "emi",
        "name": "SBI Home loan EMI",
        "date": "Wed 28 Oct",
        "short": "28 Oct",
        "amount": 38500,
        "estimated": False,
        "status": "later",
        "late": "",
        "source": "Loan · ₹9,320 principal · ₹29,180 interest",
        "schedule": None,
        "from": "SBI Salary",
        "to": "SBI Home loan",
        "cls": "committed",
        "icon": "house",
        "color": "#2A6FDB",
        "match": None,
    },
    {
        "key": "salary",
        "name": "Salary · Acme",
        "date": "Wed 28 Oct",
        "short": "28 Oct",
        "amount": 155400,
        "estimated": True,
        "status": "later",
        "late": "",
        "source": "Schedule · estimated · 4 Postings",
        "schedule": "salary",
        "from": "Salary",
        "to": "SBI Salary",
        "cls": "income",
        "icon": "briefcase",
        "color": "#0A8754",
        "match": None,
    },
]

DONE = [
    ("Salary · Acme", "Mon 28 Sep", 155400, "Confirmed · ₹1,55,400 net", "income"),
    ("SBI Home loan EMI", "Mon 28 Sep", 38500, "Linked to a quick-add", "committed"),
    ("Netflix", "Mon 14 Sep", 649, "Auto-posted", "committed"),
    ("Europe 2028 SIP", "Thu 10 Sep", 5000, "Confirmed · 21.84 units", "savings"),
    ("Parag Parikh Flexi Cap SIP", "Sat 5 Sep", 10000, "Confirmed · 112.41 units", "savings"),
    ("PPF deposit", "Sat 5 Sep", 10000, "Auto-posted", "savings"),
    ("Airtel broadband", "Wed 2 Sep", 1179, "Confirmed at ₹1,179", "committed"),
    ("Rent to Mr. Rao", "Tue 1 Sep", 32000, "Auto-posted", "committed"),
]
