# Generated by Django 6.1.1 on 2026-10-01 08:06

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('emi_grace_period', 'EMI grace period'), ('starter_fund', 'Starter fund'), ('life_cover_multiple', 'Life cover multiple'), ('health_cover_floor', 'Health cover floor'), ('high_interest_rate', 'High-interest rate'), ('emergency_fund', 'Emergency Fund'), ('emi_cap', 'EMI cap'), ('savings_rate_target', 'Savings-rate target'), ('general_inflation', 'General inflation'), ('medical_inflation', 'Medical inflation'), ('safe_withdrawal_rate', 'Safe Withdrawal Rate'), ('decumulation_equity', 'Decumulation equity')], max_length=32, unique=True)),
                ('value', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalThreshold',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('key', models.CharField(choices=[('emi_grace_period', 'EMI grace period'), ('starter_fund', 'Starter fund'), ('life_cover_multiple', 'Life cover multiple'), ('health_cover_floor', 'Health cover floor'), ('high_interest_rate', 'High-interest rate'), ('emergency_fund', 'Emergency Fund'), ('emi_cap', 'EMI cap'), ('savings_rate_target', 'Savings-rate target'), ('general_inflation', 'General inflation'), ('medical_inflation', 'Medical inflation'), ('safe_withdrawal_rate', 'Safe Withdrawal Rate'), ('decumulation_equity', 'Decumulation equity')], db_index=True, max_length=32)),
                ('value', models.DecimalField(decimal_places=4, max_digits=16)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical threshold',
                'verbose_name_plural': 'historical thresholds',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
